### ISSUE TITLE
Filter Value 'Rate' Ignored

### ISSUE THREAD

**Issue by patmadden** [lumo93/RE-FLEX#1]
Hourly rate is not being filtered properly, resulting in blocks being booked for lower rates. My filter is set to hourly rate of 21 but it just booked me for a block at an hourly rate of 19

![python_2023-02-22_14-21-33](https://user-images.githubusercontent.com/25353047/220736579-eacf3bbd-c3cd-4a49-bd4b-fb6fe838e63e.png)

**Comment by lumo93** [comment]
Hi, I saw the updated readme as well, thank you. The reason that happened is lowprice does not take anything into account after headstart. lowprice is more of an override for the hourly and length. it's meant more for if you wanna get a few more high value blocks but they are slightly bellow the hourly. If you have any recommendations to improve on that please let me know

**Comment by patmadden** [comment]
Sure, no problem - great script so far! This makes sense, I will close this issue for now and see if I can brainstorm another solution.
