### ISSUE TITLE
What do the speed behaviours represent?

### ISSUE THREAD

**Issue by armz93** [lumo93/RE-FLEX#14]
@lumo93 Is there a key for the Set_Speeds_and_Behaviour anywhere.

I don't understand what the terms timehigh, timelow, burstvalue, bursttimehigh, bursttimelow mean.

I'm guessing it has to do with the click rate and if it misses a block then it speeds up temporarily I assume, or something like that. Can you clarify please?

**Comment by lumo93** [comment]
Sure, 

timehigh(TH)-timelow(TL) is the range for which the script will choose from for each interval between attempt, so as not to do it at a consistent interval and 'appear' more human

the bursttimehigh(BTH)-bursttimelow(BTL) function the same, but is meant as a quick succession of attempts, between each TH-TL, with burstvalue(BV) being the amount of attempts. So:

TH 10 sec
TL 5 sec

BV 6 attempts

BTH 0.6 sec
BTL 0.2 sec

The script will make 6 quick attempts at a speed of 0.2-0.6 seconds, every 5-10 seconds

BV 0 is like turning it off

**Comment by armz93** [comment]
Super helpful, thank you. So with my burstvalue set to 0, and timehigh at 2.5 and timelow at 2, does that mean it will attempt tap/refresh offers every 2 to 2.5 secs yeah?

Also, I'm hitting rate limit quite often (within an hour!) at above settings. Any recommendations? And also 45 mins ratelimit sleep doesnt seem yo be enough, it keeps hitting it soon after it restarts. Im attaching a photo for you.

Other than that, amazing work Lumo, tysm.

![16949497173178194953137788548317](https://github.com/lumo93/RE-FLEX/assets/20983636/f762181a-237b-492c-a9e7-688ae6ae2b2f)

**Comment by lumo93** [comment]
So I notice you aren't stopping the script when you change the values and speeds. Your settings don't take effect until you restart the script. And I personally use 3.5-4 seconds, which allows the script to run for longer, although might not be as competitive. At your speeds you may wanna try an hour instead, but I'm not sure if that will be much of an improvement.
