### ISSUE TITLE
Offers_outside_filters acting wierd

### ISSUE THREAD

**Issue by armz93** [lumo93/RE-FLEX#15]
Hi @lumo93 
![16951257368558875767475363581651](https://github.com/lumo93/RE-FLEX/assets/20983636/fb285c00-64ab-497b-b212-74695f31bf48)

Bot is missing blocks and I can't figure out why. See attached pic.

The filter values suggest those offers are within the filter assigned?

I don't assume the start or end time could be causing the issue? That I assume is the bot running/sleep time essentially.

**Comment by lumo93** [comment]
Your end time cannot be past 23:00, and it can't loop around to AM

So you can have 6:00 to 23:00, but you have 01:00, so it won't look for anything that ends after 1 am that day or any day

**Comment by lumo93** [comment]
Start time is when the block starts, so if you have it set to 13:00 you don't see anything for the morning. It only accounts for the start time.

End time is the reverse, so if you have it at 11:00, it won't get you anything for the afternoon, and possibly any morning shifts that end after that time

**Comment by armz93** [comment]
Thank you, now it's clear.
