### ISSUE TITLE
Error code 420 on captcha.

### ISSUE THREAD

**Issue by rootcstar** [lumo93/RE-FLEX#18]
Amazon's new update gives 420 error code on validateChallenge. Anyone saw the issue ?

**Comment by redkenusa** [comment]
Hello where you can find the error 420 ?? I was trying to install the system I do all the steps and when I turned on I open the Check_Logs and this is what I receive back 

----------------------------------
Scanned at 11/02/2023 08:34:59 PM
----------------------------------
Friday 11/03/2023 06:15 PM
Las Vegas NV (VNV2) - Sub Same-Day
29.0 x 3.0 = 87.0
11/02/2023 08:34:59 PM
------------------------------------
------------------------------------
Missed Block for 87.0 Dollars
----------------------------------

All the block I am getting on the Recent_Attempts ( **Missed Block**)

Any idea why I am getting this ??

Thanks you

**Comment by lumo93** [comment]
Script updated, fixed the 420 issue. you will need to sign in again
