### ISSUE TITLE
Missing all blocks!

### ISSUE THREAD

**Issue by armz93** [lumo93/RE-FLEX#19]
I haven't been able to pick a block since Wednesday 9:35am-ish.

I was in captcha jail which I think has elapsed since I can now manually get blocks without any captchas. I.e. blocked a few simultaneously and no captchas since yesterday.

However, bot has missed everything since captcha has elapsed.

Not sure what's up with it.

Anyone else having this issue? Or can anyone confirm that it's working for you?

**Comment by khismagilov** [comment]
doesnt work for me too

**Comment by armz93** [comment]
@lumo93 I found the solution from flexunlimited but I don't have the technical know how to integrate it.

Can you please see sdubzz solution in this thread near the bottom please!!! I need this so bad. Thank you so much whoever does this.

https://github.com/mdesilva/AmazonFlexUnlimited/issues/144

**Comment by armz93** [comment]
@khismagilov do you know how to use sdubzz solution for Lumo's fork?

**Comment by lumo93** [comment]
New fix implemented, should work now. you will need to sign in again
