### ISSUE TITLE
Registering using Authorization Code / Unique Challenge Link

### ISSUE THREAD

**Issue by ghost** [lumo93/RE-FLEX#4]
I recently found a more secure way to generate the challenge link and register, using an authorization code and unique device serial. I haven't used your repo and am not familiar with how it all works otherwise I would create a pull request, but I thought I'd share what I found.

"""To generate the challenge link:"""

import base64, uuid, secrets, hashlib
from urllib.parse import urlencode

DEVICE_TYPE = "A1MPSLFC7L5AFK" # or any other device type
"""You need to save the following 3 variables somewhere on init"""
device_serial = uuid.uuid4().hex.upper()
device_id = secrets.token_hex(8)
code_verifier = base64.urlsafe_b64encode(secrets.token_bytes(32)).rstrip(b'=').decode()

device_type = "#" + DEVICE_TYPE
client_id = (device_serial.encode() + device_type.encode()).hex()
code_challenge = base64.urlsafe_b64encode(hashlib.sha256(code_verifier.encode()).digest()).rstrip(b'=')
oauth_params = {
          "openid.oa2.response_type": "code",
          "openid.oa2.code_challenge_method": "S256",
          "openid.oa2.code_challenge": code_challenge,
          "openid.return_to": "https://www.amazon.com/ap/maplanding",
          "openid.assoc_handle": "amzn_device_na"
          "openid.identity": "http://specs.openid.net/auth/2.0/identifier_select",
          "pageId": "amzn_device_na",
          "accountStatusPolicy": "P1",
          "openid.claimed_id": "http://specs.openid.net/auth/2.0/identifier_select",
          "openid.mode": "checkid_setup",
          "openid.ns.oa2": "http://www.amazon.com/ap/ext/oauth/2",
          "openid.oa2.client_id": f"device:{client_id}",
          "openid.ns.pape": "http://specs.openid.net/extensions/pape/1.0",
          "openid.ns": "http://specs.openid.net/auth/2.0",
          "openid.pape.max_auth_age": "0",
          "openid.oa2.scope": "device_auth_access",
          "forceCaptcha": "true",
          "use_global_authentication": "false"
}
challenge_link = f"https://www.amazon.com/ap/signin?{urlencode(oauth_params)}"

"""To register, given the maplanding_url, this is the body and headers required for the request:"""

parsed_query = parse_qs(urlparse(maplanding_url).query)
authorization_code = unquote(parsed_query['openid.oa2.authorization_code'][0])
device_type = "#" + DEVICE_TYPE
client_id = (device_serial.encode() + device_type.encode()).hex()
amazon_reg_data = {
    "auth_data": {
        "client_id": client_id,
        "authorization_code": authorization_code,
        "code_verifier": code_verifier,
        "code_algorithm": "SHA-256",
        "client_domain": "DeviceLegacy"
    },
    "cookies": {
        "domain": ".amazon.com",
        "website_cookies": []
    },
    "device_metadata": {
        "android_id": device_id,
        "device_os_family": "android",
        "device_serial": device_serial,
        "device_type": DEVICE_TYPE,
        "mac_address": secrets.token_hex(64).upper(),
        "manufacturer": MANUFACTURER,
        "model": DEVICE_NAME,
        "os_version": "30",
        "product": DEVICE_NAME
    },
    "registration_data": {
        "app_name": APP_NAME,
        "app_version": APP_VERSION,
        "device_model": DEVICE_NAME,
        "device_serial": device_id,
        "device_type": DEVICE_TYPE,
        "domain": "Device",
        "os_version": OS_VERSION,
        "software_version": "130050002"
    },
    "requested_extensions": [
        "device_info",
        "customer_info"
    ],
    "requested_token_type": [
        "bearer",
        "mac_dms",
        "store_authentication_cookie",
        "website_cookies"
    ],
    "user_context_map": {
        "frc": generate_frc(device_id)
    }
}
url = 'https://api.amazon.com/auth/register'
reg_headers = {
    "User-Agent": USER_AGENT,
    "Content-Type": "application/json",
    "Accept-Charset": "utf-8",
    "x-amzn-identity-auth-domain": "api.amazon.com",
    "Connection": "keep-alive",
    "Accept": "*/*",
    "Accept-Language": "en-US"
}
""" Everything else remains the same after this point """

**Comment by lumo93** [comment]
Most I have used was UUID4 and maybe secrets, everything else is entirely new to me. But thank you. I'll have to learn what all this is since I've never used any of it before. But I'll work to implement it.

This would be great, as I believe I got the original link from you I think. I recognize your name from a contribution in Amazon Flex Unlimited. I could be wrong.

**Comment by ghost** [comment]
@lumo93 yeah I contributed to Flex Unlimited. To add this change it shouldn't be too difficult. I'm just not sure where you want to store the code_verifier, device_serial, and device_id . Treat those variables like you would the refresh token.

The code under """To register, given the maplanding_url, this is the body and headers required for the request:""" --
Replace the corresponding code in register_account of register.py . You'll need to load in those 3 variables I just mentioned for that function.

The code under """To generate the challenge link:""" --
In registerCycle.py, replace the challengelinkstatic variable with this code. Just make sure you store the 3 variables I mentioned so you can load them in register.py

**Comment by lumo93** [comment]
Awesome thank you, I'll keep the issue open until I've added the changes.

**Comment by ghost** [comment]
I realized I forgot to include collecting the amz account id. You can do this when you collect the tokens near the end of register_account
amz_account_id = res['response']['success']['extensions']['customer_info']['user_id']
No problem.

**Comment by lumo93** [comment]
Cool, I'll put some work in tonight

**Comment by lumo93** [comment]
@ssmusic19 I have implemented the changes successfully and also dealt with an unrelated issue, will be uploading soon

**Comment by lumo93** [comment]
It has been implemented, will be closing this now

**Comment by ghost** [comment]
Great work on this script btw! I haven't tested it but I saw some screenshots, looks very accessible and convenient with the GUI interface, keep it up!

**Comment by lumo93** [comment]
Honestly thank you for your help, you kind of reignited my passion for this
