### ISSUE TITLE
Add more filter so user can create Available time 

### ISSUE THREAD

**Issue by Bang77777** [lumo93/RE-FLEX#7]
Hi, 
Can you add a filter like user can accept the block  by setting his available time.

Available time should be starting of available and ending of the available.

Example: user want to accept blocks from only morning 9 to evening 6 remaining should not be rejected.

If you made this means it will be helpful.

**Comment by lumo93** [comment]
Hey, I actually have something like this already
![Screenshot_20230710_051718_RVNC Viewer.jpg](https://github.com/lumo93/RE-FLEX/assets/31253518/2c1046bd-4e1e-4c2c-ba4c-5b50281d8c95)

It's in Set_Speeds_and_Behavior. You can download the repo for this if you haven't already but you will have to delete your old speeds_and_behavior.py file in your userdata folder to prevent any errors.

**Comment by Bang77777** [comment]
No it's actually not working on what  i said.

My concern is that script is should accept the blocks inbetween selected start time to end time, but it is not working. Please look into that it may be the great help from you.

**Comment by lumo93** [comment]
Can you specify how it's not working, because it works perfectly fine for me. It's in 24 hour format so pm is 12:00 to 23:00, am is 1:00 to 11:00. I try to avoid using 0:00. Please get back to me with more details of how it's not working.

**Comment by Bang77777** [comment]
Yeah Actually i saw that in your code i think you are not used start time and end time in filters and even main program can please check it once, 

My concern is scanning should be continuously run but it accept the blocks only inbetween start and end time.

Please check it once.

**Comment by lumo93** [comment]
Can you try a fresh download, the way this works is through json_data.py. it should also show in the Offers_Outside_Filters for any that are outside of your time range.

**Comment by Bang77777** [comment]
I have tried but it's not working with my case, but it is ok , you have done great job , big salute to you from flex drivers.
